baseURL: "https://cleaning-marketplace.com"
languageCode: en-us
title: Cleaning Marketplace!
theme: hugo-PaperMod

params:
  homeInfoParams:
    Title: "Cleaning Market Place"
    Content: Your one-stop shop for cleaning tips, advice and finding local cleaning services near you!

  cover:
    LinkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
