baseURL: "https://cleaning-marketplace.com"
languageCode: en-us
title: Cleaning Marketplace!
theme: hugo-PaperMod
description: Cleaning marketplace is a one-stop shop for customers and professional cleaners to connect and find helpful cleaning tips, tricks, life hacks and solutions.
env: production

params:
  homeInfoParams:
    Title: "Cleaning Marketplace"
    Content: Cleaning marketplace is a one-stop shop for customers and professional cleaners to connect and find helpful cleaning tips, tricks, life hacks and solutions.

  privacy: https://cleaning-marketplace.com/privacy/

  label:
    icon: "img/logo.svg"

  cover:
    linkFullImages: false

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowToc: true

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: cleaning-tips
      name: Cleaning Tips
      url: /tips/
      weight: 20
    - identifier: contact
      name: Contact Us
      url: /contact/
      weight: 30
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 31
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 32
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 33
